package com.bank.bian.transactionengine;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Transaction Engine
 *
 * Business Area:      Operations and Execution
 * Business Domain:    Operations
 * Functional Pattern: Operate
 * Asset Type:         Transaction Ledger
 * Control Record:     Transaction Ledger Operating Session
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Transaction Engine — BIAN Semantic API")
                .description("Service Domain 'Transaction Engine' (Operate pattern) "
                        + "operating on the 'Transaction Ledger Operating Session' control record.")
                .version("0.1.0"));
    }
}
